export const projects = [
  {
    id: 1,
    title: "Vişne Mermer — GLAM Collection",
    description: "MDFLAM Panel, High-Gloss Finish, Premium Surface",
    image: "/stories/story1.png",
    column: 1,
  },
  {
    id: 2,
    title: "Kobalt Mavi — Super Gloss",
    description: "Lak Panel, Ultra-Glossy Finish, Dramatic Impact",
    image: "/stories/story2.png",
    column: 1,
  },
  {
    id: 3,
    title: "Terra Rosso — Kapak Panel",
    description: "Premium Panel, Rich Red Finish, Bold Statement",
    image: "/stories/story3.png",
    column: 1,
  },
  {
    id: 4,
    title: "Mistik Mürdüm — GLAM Series",
    description: "MDFLAM Panel, Mystical Purple, Elegant Finish",
    image: "/stories/story4.png",
    column: 1,
  },
  {
    id: 5,
    title: "Ihlamur Yeşili — CALM Collection",
    description: "MDFLAM Panel, Natural Green, Tranquil Finish",
    image: "/stories/story5.png",
    column: 2,
  },
  {
    id: 6,
    title: "Zen Traverten — Natural Stone",
    description: "MDFLAM Panel, Stone Effect, Peaceful Aesthetic",
    image: "/stories/story6.png",
    column: 2,
  },
  {
    id: 7,
    title: "Kutup Taşı — Kapak Panel",
    description: "Premium Panel, Arctic Stone, Serene Finish",
    image: "/stories/story7.png",
    column: 2,
  },
  {
    id: 8,
    title: "Duru Mermer — Pure Elegance",
    description: "Kapak Panel, Pure Marble, Timeless Beauty",
    image: "/stories/story8.png",
    column: 2,
  },
];
